name: Create Stable Release

on: [ push, pull_request, workflow_dispatch ]

# for release create
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt install llvm

    - name: Fetch OpenOrbis
      run: curl -sL https://github.com/StevenMiller123/OpenOrbis-PS4-Toolchain/releases/latest/download/openorbis_toolchain.tar.gz | tar xz -C ./

    - name: Checkout GoldHEN Plugins SDK
      uses: actions/checkout@main
      with:
        repository: GoldHEN/GoldHEN_Plugins_SDK
        path: Plugins-SDK
    
    - name: Build Plugins SDK
      working-directory: "Plugins-SDK"
      run: make all
    
    - name: Checkout Plugin
      uses: actions/checkout@main
      with:
        submodules: recursive

    - name: Compile Plugin
      env:
        OO_PS4_TOOLCHAIN: "${{ github.workspace }}/OpenOrbis/PS4Toolchain"
        GOLDHEN_SDK: "${{ github.workspace }}/Plugins-SDK"
      run: |
        cmake -S . -B build
        cmake --build build --parallel $(nproc)
    
    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create release-${{ GITHUB.SHA }} build/prx_final/shadNet-PS4.prx --target ${{ GITHUB.SHA }} -t "Automated Release ${{ GITHUB.SHA }}"